HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
    systembindir: /opt/puppetlabs/agent/bin
    puppetconfdir: /etc/puppetlabs/agent
    puppetcodedir: /etc/puppetlabs/agent
    puppetvardir: /opt/puppetlabs/agent/cache
    distmoduledir: /etc/puppetlabs/agent/modules
    sitemoduledir: /opt/puppetlabs/agent/modules
    hieraconf: /etc/puppetlabs/puppet/hiera.yaml
  agent:
    roles:
      - agent
    platform: el-7-x86_64
    hypervisor: vcloud
    template: redhat-7-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
